using System.Data;
using Npgsql;

namespace PostgresPractice;

public static class Database
{
    const string ConnectionString =
        "Host=127.0.0.1;Port=5433;Username=admin;Password=admin1234;Database=AppPgDb;";

    public static IDbConnection Open()
    {
        NpgsqlConnection conn = new NpgsqlConnection(ConnectionString);
        conn.Open();
        return conn;
    }
    
    public static void EnsureSchema()
    {
        using (IDbConnection conn = Database.Open())
        using (IDbCommand cmd = conn.CreateCommand())
        {
            cmd.CommandText = @"
                CREATE TABLE IF NOT EXISTS Users(
        UserId INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        Username TEXT NOT NULL UNIQUE,
        PasswordHash TEXT NOT NULL,
        FirstName TEXT NOT NULL,
        LastName TEXT NOT NULL,
        DateOfBirth TEXT NOT NULL,
        CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS Friends(
        UserId INTEGER NOT NULL,
        FriendUserId INTEGER NOT NULL,
        CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

        CONSTRAINT PK_Friends 
            PRIMARY KEY (UserId, FriendUserId),

        CONSTRAINT FK_Friends_Users 
            FOREIGN KEY (UserId) 
            REFERENCES Users(UserId) 
            ON DELETE CASCADE,

        CONSTRAINT FK_Friends_Friend 
            FOREIGN KEY (FriendUserId) 
            REFERENCES Users(UserId) 
            ON DELETE CASCADE);
         
           ";
            
            cmd.ExecuteNonQuery();
        }
    }

}